import type { DoctorMission } from "@/lib/onboarding/doctor/types";

export const DOCTOR_MISSIONS: DoctorMission[] = [
  {
    id: "workspace",
    stage: 1,
    stageLabel: "Workspace",
    title: "Explore your clinic dashboard",
    description: "Review live ops metrics, patient counts, and performance at a glance.",
    route: "/portal/doctor",
    estimatedMinutes: 3,
  },
  {
    id: "practice",
    stage: 2,
    stageLabel: "Foundation",
    title: "Complete clinic profile",
    description: "Add practice details, branding, banking, and notification defaults.",
    route: "/portal/doctor/settings",
    estimatedMinutes: 12,
    requiredPermission: "edit_clinic",
  },
  {
    id: "catalog",
    stage: 3,
    stageLabel: "Catalog",
    title: "Browse inventory & add products",
    description: "Search the master catalog and add your first product to My Store.",
    route: "/portal/doctor/inventory",
    estimatedMinutes: 8,
  },
  {
    id: "storefront",
    stage: 4,
    stageLabel: "Storefront",
    title: "Launch your patient storefront",
    description: "Set retail pricing and make products visible to patients.",
    route: "/portal/doctor/my-store",
    estimatedMinutes: 7,
  },
  {
    id: "patients",
    stage: 5,
    stageLabel: "Patients",
    title: "Invite your first patient",
    description: "Send a secure invitation so patients can browse and order.",
    route: "/portal/doctor/customers",
    estimatedMinutes: 5,
    requiredPermission: "invite_patients",
    skipWithoutPermission: true,
  },
  {
    id: "orders",
    stage: 6,
    stageLabel: "Operations",
    title: "Learn the order workflow",
    description: "Understand how to review, approve, and track patient orders.",
    route: "/portal/doctor/orders",
    estimatedMinutes: 5,
  },
  {
    id: "messages",
    stage: 7,
    stageLabel: "Connect",
    title: "Set up patient messaging",
    description: "Use secure chat for clinical questions and order updates.",
    route: "/portal/doctor/messages",
    estimatedMinutes: 4,
  },
  {
    id: "team",
    stage: 8,
    stageLabel: "Team",
    title: "Invite your team",
    description: "Add staff or associate providers to help manage the clinic.",
    route: "/portal/doctor/users",
    estimatedMinutes: 6,
    requiredPermission: "manage_members",
    skipWithoutPermission: true,
  },
  {
    id: "accounting",
    stage: 9,
    stageLabel: "Finance",
    title: "Review revenue & payouts",
    description: "Explore financial reporting and payout breakdowns.",
    route: "/portal/doctor/accounting",
    estimatedMinutes: 4,
  },
  {
    id: "support",
    stage: 10,
    stageLabel: "Support",
    title: "Know where to get help",
    description: "Find answers in the knowledge base or submit a support ticket.",
    route: "/portal/doctor/help",
    estimatedMinutes: 3,
  },
];

export const DOCTOR_ONBOARDING_TITLE = "Clinic launch guide";
export const DOCTOR_ONBOARDING_SUBTITLE =
  "A guided setup across your entire portal — complete each mission to go live with confidence.";
